package jetbrains.mps.graphLayout.planarGraph;

/*Generated by MPS */

import jetbrains.mps.graphLayout.graph.Edge;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class CheckEmbeddedGraph {
  public static void checkAdjacentFaces(EmbeddedGraph embeddedGraph) {
    for (Edge edge : SetSequence.fromSet(embeddedGraph.getEdges())) {
      if (ListSequence.fromList(embeddedGraph.getAdjacentFaces(edge)).count() != 2) {
        throw new RuntimeException("bad adjacent list");
      }
    }
  }

  public static void checkEmbeddedGraph(EmbeddedGraph embeddedGraph) {
    checkAdjacentFaces(embeddedGraph);
    for (Face face : ListSequence.fromList(embeddedGraph.getFaces())) {
      if (!(CheckFace.check(face))) {
        throw new RuntimeException("bad face: " + face);
      }
    }
  }
}
