package jetbrains.mps.xml.deprecated.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import org.jdom.DocType;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class ExternalId_Behavior {
  private static Class[] PARAMETERS_1234406619968 = {SNode.class ,DocType.class};

  public static void init(SNode thisNode) {
  }

  public static void call_createID_1234406619968(SNode thisNode, DocType doctype) {
    BehaviorManager.getInstance().invoke(Object.class, thisNode, "virtual_createID_1234406619968", PARAMETERS_1234406619968, doctype);
  }

  public static void callSuper_createID_1234406619968(SNode thisNode, String callerConceptFqName, DocType doctype) {
    BehaviorManager.getInstance().invokeSuper(Object.class, thisNode, callerConceptFqName, "virtual_createID_1234406619968", PARAMETERS_1234406619968, doctype);
  }

}
