package jetbrains.mps.baseLanguage.dates.behavior;

/*Generated by MPS */


public class CeilingDateTimeOperation_BehaviorDescriptor extends RoundDateTimeOperation_BehaviorDescriptor {
  public CeilingDateTimeOperation_BehaviorDescriptor() {
  }
}
