package jetbrains.mps.xmlQuery.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.xmlQuery.constraints.SchemaUtil;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class ElementBuilder_Behavior {
  private static Class[] PARAMETERS_1384720974900260447 = {SNode.class};
  private static Class[] PARAMETERS_1384720974900260456 = {SNode.class ,SNode.class};
  private static Class[] PARAMETERS_1384720974900260473 = {SNode.class ,SNode.class ,SNode.class ,SNode.class};

  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getResultType_7057666463730718251(SNode thisNode) {
    return SchemaUtil.constructXMLElementTypeForElement(SLinkOperations.getTarget(thisNode, "elementDeclaration", false));
  }

  public static SNode virtual_getCreatorExpression_7057666463730727863(SNode thisNode, SNode parentRef) {
    return new _Quotations.QuotationClass_3().createNode(SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "elementDeclaration", false), "elementName"));
  }

  public static SNode virtual_getAttachStatementChild_4797501453850305563(SNode thisNode, SNode parentBuilder, SNode parentRef, SNode childRef) {
    return new _Quotations.QuotationClass_4().createNode(parentRef, childRef);
  }

  public static SNode call_getComplexType_1384720974900281910(SNode thisNode) {
    if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(thisNode, "elementDeclaration", false), "jetbrains.mps.xmlSchema.structure.ElementWithType")) {
      return SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(thisNode, "elementDeclaration", false), "jetbrains.mps.xmlSchema.structure.ElementWithType"), "complexTypeReference", true), "complexType", false);
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(thisNode, "elementDeclaration", false), "jetbrains.mps.xmlSchema.structure.ElementWithContent")) {
      return SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(thisNode, "elementDeclaration", false), "jetbrains.mps.xmlSchema.structure.ElementWithContent"), "complexType", true);
    } else {
      assert false;
      return null;
    }
  }

  public static SNode call_getResultType_1384720974900260447(SNode thisNode) {
    return (SNode)BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.xmlQuery.structure.ElementBuilder"), "virtual_getResultType_7057666463730718251", PARAMETERS_1384720974900260447);
  }

  public static SNode call_getCreatorExpression_1384720974900260456(SNode thisNode, SNode parentRef) {
    return (SNode)BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.xmlQuery.structure.ElementBuilder"), "virtual_getCreatorExpression_7057666463730727863", PARAMETERS_1384720974900260456, parentRef);
  }

  public static SNode call_getAttachStatementChild_1384720974900260473(SNode thisNode, SNode parentBuilder, SNode parentRef, SNode childRef) {
    return (SNode)BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.xmlQuery.structure.ElementBuilder"), "virtual_getAttachStatementChild_4797501453850305563", PARAMETERS_1384720974900260473, parentBuilder, parentRef, childRef);
  }

  public static SNode callSuper_getResultType_1384720974900260447(SNode thisNode, String callerConceptFqName) {
    return (SNode)BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.xmlQuery.structure.ElementBuilder"), callerConceptFqName, "virtual_getResultType_7057666463730718251", PARAMETERS_1384720974900260447);
  }

  public static SNode callSuper_getCreatorExpression_1384720974900260456(SNode thisNode, String callerConceptFqName, SNode parentRef) {
    return (SNode)BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.xmlQuery.structure.ElementBuilder"), callerConceptFqName, "virtual_getCreatorExpression_7057666463730727863", PARAMETERS_1384720974900260456, parentRef);
  }

  public static SNode callSuper_getAttachStatementChild_1384720974900260473(SNode thisNode, String callerConceptFqName, SNode parentBuilder, SNode parentRef, SNode childRef) {
    return (SNode)BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.xmlQuery.structure.ElementBuilder"), callerConceptFqName, "virtual_getAttachStatementChild_4797501453850305563", PARAMETERS_1384720974900260473, parentBuilder, parentRef, childRef);
  }
}
