package jetbrains.mps.xml.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Error;
import jetbrains.mps.nodeEditor.cells.EditorCell_Label;

public class Content_Editor extends DefaultNodeEditor {

  public EditorCell createEditorCell(EditorContext context, SNode node) {
    return this.createError1166803177963(context, node);
  }

  public EditorCell createError1166803177963(EditorContext context, SNode node) {
    EditorCell_Error editorCell = new EditorCell_Error(context, node, "content");
    setupBasic_Error_11668031779631166803177963(editorCell, node, context);
    setupLabel_Error_1166803177963_1166803177963(editorCell, node, context);
    return editorCell;
  }


  private static void setupBasic_Error_11668031779631166803177963(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setCellId("Error_1166803177963");
  }

  private static void setupLabel_Error_1166803177963_1166803177963(EditorCell_Label editorCell, SNode node, EditorContext context) {
  }

}
