package jetbrains.mps.baseLanguage.dates.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.baseLanguage.editor.BaseLanguageStyle_StyleSheet;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.editor.runtime.style.Padding;
import jetbrains.mps.editor.runtime.style.Measure;
import jetbrains.mps.openapi.editor.style.StyleRegistry;
import jetbrains.mps.nodeEditor.MPSColors;
import jetbrains.mps.nodeEditor.MPSFonts;

public class Dates_StyleSheet {
  public static void apply_DateCompactKeyWord(Style style, EditorCell editorCell) {
    BaseLanguageStyle_StyleSheet.apply_CompactKeyWord(style, editorCell);
  }

  public static void apply_DateSmall(Style style, EditorCell editorCell) {
    style.set(StyleAttributes.SELECTABLE, false);
    style.set(StyleAttributes.FONT_SIZE, 9);
    style.set(StyleAttributes.PADDING_RIGHT, new Padding(1.0, Measure.SPACES));
    style.set(StyleAttributes.TEXT_COLOR, StyleRegistry.getInstance().getSimpleColor(MPSColors.gray));
  }

  public static void apply_DateFormat(Style style, EditorCell editorCell) {
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.PLAIN);
    style.set(StyleAttributes.TEXT_COLOR, StyleRegistry.getInstance().getSimpleColor(MPSColors.DARK_MAGENTA));
    style.set(StyleAttributes.PADDING_RIGHT, new Padding(0.0, Measure.SPACES));
  }

  public static void apply_DateProperty(Style style, EditorCell editorCell) {
    BaseLanguageStyle_StyleSheet.apply_Field(style, editorCell);
  }


}
