package jetbrains.mps.baseLanguage.dates.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;

public class TokenCondition_datetimeToFormat_Behavior {
  public static void init(SNode thisNode) {
  }
  public static SNode virtual_getType_2443692612523876968(SNode thisNode) {
    return _quotation_createNode_ru4e3n_a0a0();
  }
  private static SNode _quotation_createNode_ru4e3n_a0a0() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode quotedNode_1 = null;
    quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.dates.structure.DateTimeType", null, null, false);
    return quotedNode_1;
  }
}
