package jetbrains.mps.graphLayout.planarization;

/*Generated by MPS */


public class EmbeddingFinderFactory {
  public static IEmbeddingFinder getFinder() {
    return new ShortestPathEmbeddingFinder(new PQPlanarizationFinder());
  }
}
