package jetbrains.mps.xml.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.UUID;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptAttribute = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.Attribute", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1167700349452L)).super_("jetbrains.mps.xml.structure.BaseAttribute").super_(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1165235274815L)).parents("jetbrains.mps.xml.structure.BaseAttribute", "jetbrains.mps.lang.core.structure.IDontSubstituteByDefault").parentIds(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1165235274815L), MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1835621062190663819L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(1167701332877L, "attributeDeclaration", MetaIdFactory.conceptId(UUID.fromString("b51b9e02-45dc-4b48-b300-cf49360a8d1f"), 1167697887602L), false)).references("attributeDeclaration").childDescriptors(new ConceptDescriptorBuilder.Link(1167703268127L, "value", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163340203555L), false, false, false)).children(new String[]{"value"}, new boolean[]{false}).create();
  /*package*/ final ConceptDescriptor myConceptBaseAttribute = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.BaseAttribute", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1165235274815L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptBaseElement = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.BaseElement", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1179102053371L)).super_("jetbrains.mps.xml.structure.Content").super_(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L)).parents("jetbrains.mps.xml.structure.Content").parentIds(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L)).childDescriptors(new ConceptDescriptorBuilder.Link(1179114219774L, "contentList", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163629230879L), false, false, false), new ConceptDescriptorBuilder.Link(1188768803246L, "attribute", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1165235274815L), true, true, false)).children(new String[]{"contentList", "attribute"}, new boolean[]{false, true}).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptBaseText = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.BaseText", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163340203555L)).super_("jetbrains.mps.xml.structure.Content").super_(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L)).parents("jetbrains.mps.xml.structure.Content").parentIds(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptCDATA = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.CDATA", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1192038615503L)).super_("jetbrains.mps.xml.structure.Content").super_(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L)).parents("jetbrains.mps.xml.structure.Content").parentIds(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L)).childDescriptors(new ConceptDescriptorBuilder.Link(1192038646485L, "contentList", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163629230879L), false, false, false)).children(new String[]{"contentList"}, new boolean[]{false}).alias("CDATA", "").create();
  /*package*/ final ConceptDescriptor myConceptComplexText = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.ComplexText", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161911457732L)).super_("jetbrains.mps.xml.structure.BaseText").super_(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163340203555L)).parents("jetbrains.mps.xml.structure.BaseText").parentIds(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163340203555L)).childDescriptors(new ConceptDescriptorBuilder.Link(1161911474092L, "text", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163340203555L), false, true, false)).children(new String[]{"text"}, new boolean[]{true}).alias("*complexText", "").create();
  /*package*/ final ConceptDescriptor myConceptContent = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.Content", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptContentList = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.ContentList", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163629230879L)).super_("jetbrains.mps.xml.structure.Content").super_(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L)).parents("jetbrains.mps.xml.structure.Content").parentIds(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1166231449055L, "isHorizontal")).properties("isHorizontal").childDescriptors(new ConceptDescriptorBuilder.Link(1163629255661L, "content", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161371727643L), true, true, false)).children(new String[]{"content"}, new boolean[]{true}).alias("(contentList)", "").create();
  /*package*/ final ConceptDescriptor myConceptElement = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.Element", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1167523027466L)).super_("jetbrains.mps.xml.structure.BaseElement").super_(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1179102053371L)).parents("jetbrains.mps.xml.structure.BaseElement", "jetbrains.mps.lang.core.structure.IDontSubstituteByDefault").parentIds(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1179102053371L), MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1835621062190663819L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1172970532917L, "isEmpty")).properties("isEmpty").referenceDescriptors(new ConceptDescriptorBuilder.Ref(1167523262932L, "elementDeclaration", MetaIdFactory.conceptId(UUID.fromString("b51b9e02-45dc-4b48-b300-cf49360a8d1f"), 1167838236835L), false)).references("elementDeclaration").create();
  /*package*/ final ConceptDescriptor myConceptEntityReference = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.EntityReference", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1172960673168L)).super_("jetbrains.mps.xml.structure.BaseText").super_(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163340203555L)).parents("jetbrains.mps.xml.structure.BaseText").parentIds(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163340203555L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(1172960837561L, "entityDeclaration", MetaIdFactory.conceptId(UUID.fromString("b51b9e02-45dc-4b48-b300-cf49360a8d1f"), 1172950047361L), false)).references("entityDeclaration").alias("&entity;", "").create();
  /*package*/ final ConceptDescriptor myConceptText = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.Text", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1161373262136L)).super_("jetbrains.mps.xml.structure.BaseText").super_(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163340203555L)).parents("jetbrains.mps.xml.structure.BaseText", "jetbrains.mps.lang.core.structure.IDontSubstituteByDefault").parentIds(MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1163340203555L), MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1835621062190663819L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1161373273669L, "text")).properties("text").alias("/text", "plain text").create();
  /*package*/ final ConceptDescriptor myConceptXmlRoot = new ConceptDescriptorBuilder("jetbrains.mps.xml.structure.XmlRoot", MetaIdFactory.conceptId(UUID.fromString("2c55c7ac-60c3-4eea-b9db-0d627bd2dcb9"), 1198862578220L)).interface_().create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAttribute, myConceptBaseAttribute, myConceptBaseElement, myConceptBaseText, myConceptCDATA, myConceptComplexText, myConceptContent, myConceptContentList, myConceptElement, myConceptEntityReference, myConceptText, myConceptXmlRoot);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0q, conceptFqName)) {
      case 0:
        return myConceptAttribute;
      case 1:
        return myConceptBaseAttribute;
      case 2:
        return myConceptBaseElement;
      case 3:
        return myConceptBaseText;
      case 4:
        return myConceptCDATA;
      case 5:
        return myConceptComplexText;
      case 6:
        return myConceptContent;
      case 7:
        return myConceptContentList;
      case 8:
        return myConceptElement;
      case 9:
        return myConceptEntityReference;
      case 10:
        return myConceptText;
      case 11:
        return myConceptXmlRoot;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0q = new String[]{"jetbrains.mps.xml.structure.Attribute", "jetbrains.mps.xml.structure.BaseAttribute", "jetbrains.mps.xml.structure.BaseElement", "jetbrains.mps.xml.structure.BaseText", "jetbrains.mps.xml.structure.CDATA", "jetbrains.mps.xml.structure.ComplexText", "jetbrains.mps.xml.structure.Content", "jetbrains.mps.xml.structure.ContentList", "jetbrains.mps.xml.structure.Element", "jetbrains.mps.xml.structure.EntityReference", "jetbrains.mps.xml.structure.Text", "jetbrains.mps.xml.structure.XmlRoot"};
}
