package jetbrains.mps.xmlSchema.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.style.Style;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.style.StyleAttributes;
import jetbrains.mps.nodeEditor.style.AttributeCalculator;
import java.awt.Color;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.nodeEditor.MPSFonts;

public class XmlSchema_StyleSheet {

  public static Style getXmlElement(final EditorCell cell) {
    return new Style(cell) {
      {
        this.set(StyleAttributes.TEXT_COLOR, new AttributeCalculator <Color>() {

          public Color calculate(EditorCell cell) {
            return XmlSchema_StyleSheet.calculateColor9352_0(cell);
          }

        });
        this.set(StyleAttributes.FONT_STYLE, new AttributeCalculator <Integer>() {

          public Integer calculate(EditorCell cell) {
            return XmlSchema_StyleSheet.calculateFontStyle9352_0(cell);
          }

        });
      }

    };
  }

  public static Color _StyleParameter_QueryFunction_1189991412577(SNode node, EditorContext editorContext) {
    return XmlColorConstants.XML_COLOR;
  }

  private static Integer calculateFontStyle9352_0(EditorCell cell) {
    int result;
    result = MPSFonts.BOLD;
    return result;
  }

  private static Color calculateColor9352_0(EditorCell cell) {
    Color result;
    result = XmlSchema_StyleSheet._StyleParameter_QueryFunction_1189991412577((cell == null ?
      null :
      cell.getSNode()
    ), (cell == null ?
      null :
      cell.getEditorContext()
    ));
    return result;
  }

}
