package jetbrains.mps.baseLanguage.dates.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class TimeZoneIDExpression_Behavior {
  public static void init(SNode thisNode) {
  }
}
