package jetbrains.mps.xml.deprecated.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Error;
import jetbrains.mps.nodeEditor.cells.EditorCell_Label;

public class ElementPart_Editor extends DefaultNodeEditor {

  public EditorCell createEditorCell(EditorContext context, SNode node) {
    return this.createError1119977874007(context, node);
  }

  public EditorCell createError1119977874007(EditorContext context, SNode node) {
    EditorCell_Error editorCell = new EditorCell_Error(context, node, "<choose content>");
    setupBasic_Error_11199778740071119977874007(editorCell, node, context);
    setupLabel_Error_1119977874007_1119977874007(editorCell, node, context);
    return editorCell;
  }


  private static void setupBasic_Error_11199778740071119977874007(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.putUserObject(EditorCell.CELL_ID, "Error_1119977874007");
  }

  private static void setupLabel_Error_1119977874007_1119977874007(EditorCell_Label editorCell, SNode node, EditorContext context) {
  }

}
