package planarizationTest;

/*Generated by MPS */

import junit.framework.TestCase;
import jetbrains.mps.graphLayout.graph.Graph;
import sampleGraphs.SimpleDirectedGraphs;
import visualization.GraphIO;
import java.util.Scanner;
import jetbrains.mps.graphLayout.planarization.TreeEmbeddingFinder;
import jetbrains.mps.graphLayout.planarGraph.EmbeddedGraph;

public class TreeEmbeddingFinder_Find_Test extends TestCase {
  public void test_triangle() throws Exception {
    Graph graph = SimpleDirectedGraphs.triangle();
    test(graph);
  }

  public void test_test1() throws Exception {
    String graphString = "4 5  0 1  0 3  1 2  1 3  2 3";
    test(GraphIO.scanGraph(new Scanner(graphString)));
  }

  public void test_test2() throws Exception {
    String graphString = "5 6  0 1  0 3  1 2  1 3  2 3  0 4";
    test(GraphIO.scanGraph(new Scanner(graphString)));
  }

  public void test(Graph graph) {
    TreeEmbeddingFinder embeddingFinder = new TreeEmbeddingFinder();
    EmbeddedGraph embeddedGraph = embeddingFinder.find(graph);
    /*
      System.out.println(embeddedGraph);
    */
  }
}
