package jetbrains.mps.xmlInternal.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.DescriptorProvider;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;

public class BehaviorAspectDescriptor extends DescriptorProvider<BehaviorDescriptor> {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch ((fqName).hashCode()) {
      case 459650392:
        return new StatementElement_BehaviorDescriptor();
      case -770580543:
        return new ContentStatement_BehaviorDescriptor();
      case -1907285240:
        return new XmlFile_BehaviorDescriptor();
      case 2068094694:
        return new Document_BehaviorDescriptor();
      case 989313844:
        return new Comment_BehaviorDescriptor();
      case -1171124951:
        return new DocumentStatement_BehaviorDescriptor();
      case -1809835518:
        return new Prolog_BehaviorDescriptor();
      case 1324766746:
        return new DocumentTypeDeclaration_BehaviorDescriptor();
      case -2015679151:
        // interface or abstract concept behavior jetbrains.mps.xmlInternal.structure.ExternalId 
        return null;
      case 1965348954:
        return new PublicExternalId_BehaviorDescriptor();
      case 221375876:
        return new Literal_BehaviorDescriptor();
      case -681332225:
        return new SimpleElement_BehaviorDescriptor();
      case -1653634849:
        return new SimpleAttribute_BehaviorDescriptor();
      case -1253664884:
        return new NamespaceAttribute_BehaviorDescriptor();
      default:
        return null;
    }
  }
}
