package jetbrains.mps.execution.configurations.deprecated.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunctionParameter_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class Node_FunctionParameter_BehaviorDescriptor extends ConceptFunctionParameter_BehaviorDescriptor implements IJavaRunConfigurationParameter_BehaviorDescriptor {
  public Node_FunctionParameter_BehaviorDescriptor() {
  }
  public SNode virtual_getParameterType_1810772216404820824(SNode thisNode) {
    return Node_FunctionParameter_Behavior.virtual_getParameterType_1810772216404820824(thisNode);
  }
  public SNode virtual_getType_2443692612523876968(SNode thisNode) {
    return Node_FunctionParameter_Behavior.virtual_getType_2443692612523876968(thisNode);
  }
  public String virtual_getVariableForExecuteBlockName_1810772216404807669(SNode thisNode) {
    return Node_FunctionParameter_Behavior.virtual_getVariableForExecuteBlockName_1810772216404807669(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.execution.configurations.deprecated.structure.Node_FunctionParameter";
  }
}
