package jetbrains.mps.gtext.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.UUID;
import jetbrains.mps.util.SNodeOperations;

public class GDocument_Behavior {
  public static void init(SNode thisNode) {
  }
  public static String virtual_getUnitName_5067982036267369911(SNode thisNode) {
    String extension = (SPropertyOperations.getString(thisNode, MetaAdapterFactory.getProperty(new UUID(-6324114011398976607l, -8974808928016009858l), 1184639540818l, 1184639664013l, "extension")) != null ? SPropertyOperations.getString(thisNode, MetaAdapterFactory.getProperty(new UUID(-6324114011398976607l, -8974808928016009858l), 1184639540818l, 1184639664013l, "extension")).replace(".", "$") : "");
    return SNodeOperations.getModelLongName(jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations.getModel(thisNode)) + "." + SPropertyOperations.getString(thisNode, MetaAdapterFactory.getProperty(new UUID(-3554657779850784990l, -7236703803128771572l), 1169194658468l, 1169194664001l, "name")).replace(".", "$") + "$" + extension;
  }
}
