package jetbrains.mps.baseLanguage.datesInternal.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DateTimePropertySettings_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DateTimePropertySettings_BehaviorDescriptor() {
  }
}
