package jetbrains.mps.uiLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.DescriptorProvider;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;

public class BehaviorAspectDescriptor extends DescriptorProvider<BehaviorDescriptor> {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch ((fqName).hashCode()) {
      case -1810030930:
        // interface or abstract concept behavior jetbrains.mps.uiLanguage.structure.IComponentPart 
        return null;
      case -1198249653:
        return new ComponentInstance_BehaviorDescriptor();
      case -1508631292:
        return new ComponentDeclaration_BehaviorDescriptor();
      case -731274542:
        return new ComponentController_BehaviorDescriptor();
      case -446544324:
        return new AttributeValue_BehaviorDescriptor();
      case -1639504379:
        return new AttributeDeclaration_BehaviorDescriptor();
      case 686766268:
        return new BindExpression_BehaviorDescriptor();
      case -1292439824:
        return new ComponentType_BehaviorDescriptor();
      case -126195855:
        return new AttributeReferenceOperation_BehaviorDescriptor();
      case -1205720850:
        return new LayoutConstraint_BehaviorDescriptor();
      case 554713429:
        return new ComponentReference_BehaviorDescriptor();
      case -917848755:
        return new ActionHandler_BehaviorDescriptor();
      case -2123126901:
        return new Form_BehaviorDescriptor();
      case -921386466:
        return new FormPart_BehaviorDescriptor();
      case -933398064:
        // interface or abstract concept behavior jetbrains.mps.uiLanguage.structure.IComponentInstance 
        return null;
      case -2123094515:
        return new Grid_BehaviorDescriptor();
      case -1420213107:
        return new GridRow_BehaviorDescriptor();
      case -902212500:
        return new StandardDialog_BehaviorDescriptor();
      case -816683330:
        return new StandardDialogButton_BehaviorDescriptor();
      case 1369760455:
        return new AfterConstructionBlock_BehaviorDescriptor();
      case 978729852:
        return new ListElements_BehaviorDescriptor();
      case -1797106815:
        return new Scroller_BehaviorDescriptor();
      case -1106215754:
        return new ComponentCreator_BehaviorDescriptor();
      case 443190915:
        return new BeanDeclaration_BehaviorDescriptor();
      case -73425327:
        return new BeanType_BehaviorDescriptor();
      case 606176693:
        return new BeanCreator_BehaviorDescriptor();
      case 1476628167:
        return new EventDeclaration_BehaviorDescriptor();
      case 73775920:
        return new EventAccessOperation_BehaviorDescriptor();
      case -1789197086:
        return new RaiseOperation_BehaviorDescriptor();
      case 1502373177:
        return new AddListenerOperation_BehaviorDescriptor();
      case -1649351480:
        return new RemoveListenerOperation_BehaviorDescriptor();
      case 1158727440:
        return new InlineEventHandler_BehaviorDescriptor();
      case -47232524:
        return new EventHandlerReference_BehaviorDescriptor();
      case -1891415123:
        return new RaiseInternalStatement_BehaviorDescriptor();
      case 798439464:
        return new StubCellRendererInfo_BehaviorDescriptor();
      case -2117236752:
        return new CellRendererAttribute_BehaviorDescriptor();
      case 683650179:
        return new InlineRenderer_BehaviorDescriptor();
      case 1814040516:
        return new RenderingObject_BehaviorDescriptor();
      case -240486826:
        return new BeforeConstructionBlock_BehaviorDescriptor();
      case -2139766245:
        return new PngIcon_BehaviorDescriptor();
      default:
        return null;
    }
  }
}
